### ISSUE TITLE
去水印并转换成jpg

### ISSUE THREAD

**Issue by Z-fly** [misaka10843/copymanga-downloader#1]
https://gist.github.com/Z-fly/07c92d96beaa2b3ddbbd05fec300f604
这是我之前写的，可以参考一下

**Comment by Z-fly** [comment]
看来拷贝转成webp是前端做的？

**Comment by misaka10843** [comment]
去水印的话我认为还是别了qwq
（毕竟别人不容易嘛www）
但是还是会考虑做的www

**Comment by Z-fly** [comment]
![image](https://user-images.githubusercontent.com/10470892/158503096-81e3a581-89c0-4be8-8617-8f746329dde2.png)

**Comment by Z-fly** [comment]
@misaka10843 mac上报错了

**Comment by Z-fly** [comment]
try:
    while 1:
        pass
except KeyboardInterrupt:
    pass

这段给mac用就运行不了

**Comment by misaka10843** [comment]
> try: while 1: pass except KeyboardInterrupt: pass
> 
> 这段给mac用就运行不了

这个本来是因为Ctrl+C防报错的，但是早就已经名存实亡了www

新分支已经删除，分支将在测试是否能修复代理问题后合并

**Comment by Z-fly** [comment]
@misaka10843 加个QQ好友可以吗？2658041579

**Comment by Z-fly** [comment]
@misaka10843 加个QQ好友可以吗？2 6 5 8 0 4 1 5 7 9

**Comment by Z-fly** [comment]
发邮件了，加下联系方式
