### ISSUE TITLE
🐛[BUG]遇到登录问题

### ISSUE THREAD

**Issue by Bilibilimoon** [misaka10843/copymanga-downloader#100]
### 🐛 描述(Description)

我看见之前也有个人遇到了但是没看见后续解决办法了

### 📷 复现步骤(Steps to Reproduce)

![6e35ae2ef2531c0ba88ffa4e710c7a53](https://github.com/user-attachments/assets/36292c3a-5e9e-41c3-b7ab-e22918dbf6bd)

### 程序版本(Program version)

3.5.1

### 系统(OS)

Windows10~+

### 是否使用了代理(Whether a proxy is used)

No

**Comment by misaka10843** [comment]
感谢提供报错，这似乎是因为copymanga的api更新了，我会近期修一下

**Comment by misaka10843** [comment]
我这边似乎无法复现这个问题，是否能确认一下您的用户名是多少个字符吗？
![image](https://github.com/user-attachments/assets/0412b1a2-ab7d-4738-a2e7-f4aa878d9650)
报错截图中API返回了用户名问题的错误，所以可能是copymanga那边的限制

**Comment by Bilibilimoon** [comment]
用户名是bilibilimoon

**Comment by misaka10843** [comment]
> 用户名是bilibilimoon

那确定在登录信息中填写的用户名/密码是正确的吗，这个报错是因为登录功能无法进行登录所报错的，导致凭证获取不了无法get收藏

**Comment by Bilibilimoon** [comment]
> > 用户名是bilibilimoon
> 
> 那确定在登录信息中填写的用户名/密码是正确的吗，这个报错是因为登录功能无法进行登录所报错的，导致凭证获取不了无法get收藏

已经验证过账号密码能够正常登录网页端和APP

**Comment by rhine14586** [comment]
同样的问题

**Comment by misaka10843** [comment]
我这边暂时还是无法复现这个问题，尝试创建一个新的账号尝试一下？
感觉可能是账号问题，
或者如果能提供您的账号来让我在这边尝试复现问题，就请将您的账号密码发送至`misaka10843@outlook.jp`

**Comment by Bilibilimoon** [comment]
> https://github.com/misaka10843/copymanga-downloader/actions/runs/11230319799 可以尝试一下这个构建并重新设置一下就应该没有问题了

问题已解决，感激不尽！
