### ISSUE TITLE
[预留议题]该内容在您所在的地区不可用/502

### ISSUE THREAD

**Issue by misaka10843** [misaka10843/copymanga-downloader#24]
![IMG_20220629_213755](https://user-images.githubusercontent.com/69132853/176450578-7c0a088a-9fa8-47db-a4d6-2fe317c2d216.jpg)
遇见上图类似的报错的话，可能表明copymanga开始出现制裁了，在解决方案找到前可能不能访问并下载，这时请您在此issue中留下相关截图及运行log，请**不要新开issue**
感谢支持

**Comment by misaka10843** [comment]
暂且可以使用此useragent来规避（但是可能有概率无效）
`Mozilla/5.0 (Linux; Android 12; 21091116AC) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36`

**Comment by zhongfly** [comment]
建议用ios的ua

**Comment by misaka10843** [comment]
> 另外你这个是webview吧
的确是的🤣
不知道copymanga到底是在制裁一种APP还是爬虫类的都ban🤣🤣🤣

**Comment by misaka10843** [comment]
> > > 另外你这个是webview吧
> > 
> > 
> > 的确是的🤣 不知道copymanga到底是在制裁一种APP还是爬虫类的都ban🤣🤣🤣
> 
> 你这么一说我才想起我的tachiyomi打开拷贝的漫画全是鬼图，，，，

看维护作者的话是因为copymanga制裁tachiyomi所以才会这样，然后作者就删除了官方仓库中的插件转到自己库中写（但是很不稳定www）
