### ISSUE TITLE
🐛[BUG] 对非defalut分组的下载存在问题

### ISSUE THREAD

**Issue by zhongfly** [misaka10843/copymanga-downloader#25]
### 🐛 描述(Description)

代码中粗糙地把章节列表分为defalut和other_group两个组，实际上章节的分组可以通过`GET /api/v3/comic2/${漫画拼音}`这个漫画详情接口获得，部分漫画的分组不止这2个
例如《间谍过家家》 ，另有单行本(tankobon)、其他系列(other_group)2个非defalut的分组

**Comment by misaka10843** [comment]
因为没有足够的样本数，所以导致分组出现了缺少情况，因为并不知道到底有多少个，所以就没有添加其他的分组了qwq

**Comment by zhongfly** [comment]
> 因为没有足够的样本数，所以导致分组出现了缺少情况，因为并不知道到底有多少个，所以就没有添加其他的分组了qwq 准备收集下到底最多有多少个组后再开始修下吧qwq （或者使用API来看看www）

建议用api来获取准确的信息，也不麻烦啊

**Comment by misaka10843** [comment]
应该已经可以了qwq
