### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Z-fly** [misaka10843/copymanga-downloader#26]
![image](https://user-images.githubusercontent.com/10470892/177005365-fa59a740-0869-41d4-b1a5-b442fc039a2f.png)
我之前早就画了原型图
顺便问了我隔壁写QT的，感觉实现起来不算太难
@misaka10843 解决PyQT运行问题的话，可以搞下

**Comment by misaka10843** [comment]
pyQT的话现在看起来可能需要用hyper-V来开虚拟机，但是Windows安装不上🤣

**Comment by buiawpkgew1** [comment]
可以模仿[禁漫天堂QT](https://github.com/tonquer/JMComic-qt)吗

**Comment by misaka10843** [comment]
现在这个仓库可以说已经无法进行维护了，现在我都不知道还能否正常运行，我这边环境运行的话是每次请求有75%触发502，完全无法测试🤣

**Comment by misaka10843** [comment]
可以尝试使用[此仓库](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)进行UI搭建

但是因为GUI在此仓库的优先级比较低，所以如果没有其他人需要GUI的话可能不会进行维护添加qwq

**Comment by Z-fly** [comment]
其实我感觉[flet](https://github.com/flet-dev/flet)效果更好

**Comment by misaka10843** [comment]
> 其实我感觉[flet](https://github.com/flet-dev/flet)效果更好

的确也是一种选择，可能近几十天会测试一下能不能做吧，但大概率会新开仓库qwq

**Comment by misaka10843** [comment]
> 其实我感觉[flet](https://github.com/flet-dev/flet)效果更好

关于使用这个仓库的话，因为并没有一些相关的仓库可以参考，所以本人暂时还并不是特别会用（况且给的某个功能的示例代码似乎有多种，并且使用的时候会出现警告）

所以还是可能会考虑使用[PyQt-Fluent-Widgets](https://github.com/zhiyiYo/PyQt-Fluent-Widgets)或者[WingetUI](https://github.com/marticliment/WingetUI)

但是WingetUI可能只支持win10及以上，所以为了其他平台考虑还是会用到Qt

**Comment by buiawpkgew1** [comment]
https://github.com/misaka10843/copymanga-downloader/issues/71
