### ISSUE TITLE
👑[Enhancement] 使用github actions下载

### ISSUE THREAD

**Issue by buiawpkgew1** [misaka10843/copymanga-downloader#36]

**Comment by misaka10843** [comment]
其实最好感觉还是不要用GitHub actions进行下载，因为GitHub所下载可能会出现图片出错，actions时间减少等问题

但是我会尽力添加flag参数支持

**Comment by buiawpkgew1** [comment]
禁漫天堂为啥能支持github actions下载

**Comment by misaka10843** [comment]
> 禁漫天堂为啥能支持github actions下载

因为是专门为actions类型的🤣

但是这边的话更倾向于用户一个程序能完成搜索/选话/下载的流程

**Comment by buiawpkgew1** [comment]
https://github.com/hect0x7/JMComic-Crawler-Python 希望能和这个一样

**Comment by misaka10843** [comment]
> https://github.com/hect0x7/JMComic-Crawler-Python 希望能和这个一样

其实按照本程序的话添加命令行已经算是最贴近能自动下载的了，如果是使用调用的话也可以，但是命令行就是基本上使用调用的，而且本程序也已经支持半自动更新更新列表中的漫画等其他的功能，所以如果转成这种的话可能需要再次重构

**Comment by misaka10843** [comment]
大概你使用这种https://github.com/misaka10843/copymanga-downloader#%E5%91%BD%E4%BB%A4%E7%A4%BA%E4%BE%8B
也是一样的效果，就是需要自己编写一下actions脚本

**Comment by misaka10843** [comment]
如果还有问题的话可以重新打开此议题，现在先关闭啦qwq
