### ISSUE TITLE
🐛[BUG] NameError: name 'Authorization' is not defined

### ISSUE THREAD

**Issue by dfmjndm** [misaka10843/copymanga-downloader#46]
如果您需要修改设置的话可以直接到程序根目录的settings.json更改qwq
您是想搜索还是查看您的收藏？(0:导出收藏,1:搜索,2:收藏  默认1) [0/1/2] (1): 0
Traceback (most recent call last):
  File "/copymanga-downloader/main.py", line 578, in <module>
    main()
  File "/copymanga-downloader/main.py", line 572, in main
    welcome()
  File "/copymanga-downloader/main.py", line 560, in welcome
    manga_collection_backup()
  File "/copymanga-downloader/main.py", line 512, in manga_collection_backup
    if Authorization == 0:
NameError: name 'Authorization' is not defined
[root@VM-8-2-centos copymanga-downloader]# 

这个问题前面也有人提过，我这边是用的main branch的python版，也遇到了这个情况
token的话我在设置的时候输入的是“Token ×××××××××××”，获取收藏和导出收藏都失败。
不清楚什么问题，应该和架构啊系统啊这些都没关系。

**Comment by dfmjndm** [comment]
奇怪的是就算我把512行改成
![image](https://user-images.githubusercontent.com/57401901/211727229-30cbbe3a-ce39-4e1d-83a7-98efabad6cc1.png)
照样会报这个错误

**Comment by misaka10843** [comment]
因为重构的时候首先考虑的命令行参数的编写，所以并未使用正常界面进行debug，所以导致Authorization这个参数没有初始化😂

**Comment by misaka10843** [comment]
紧急修复了一下，您可以试试这个构建中的，应该不会有问题了qwq

https://github.com/misaka10843/copymanga-downloader/actions/runs/3946719018
