### ISSUE TITLE
请问有计划把这个包发到PyPI吗？

### ISSUE THREAD

**Issue by blacklein** [misaka10843/copymanga-downloader#49]
请问有计划把这个包发到PyPI吗？这样下载和更新比较方便

**Comment by blacklein** [comment]
请问我可以把这个包发到pypi吗？里面包信息留的还是这个仓库

**Comment by misaka10843** [comment]
> 请问我可以把这个包发到pypi吗？里面包信息留的还是这个仓库

可以，当然没有问题qwq

**Comment by blacklein** [comment]
pip install copymanga-dl
现在可以用pip命令安装啦

**Comment by misaka10843** [comment]
> pip install copymanga-dl 现在可以用pip命令安装啦

好的，感谢大佬发到pypi qwq

**Comment by blacklein** [comment]
我刚入门的菜鸟，只会这点简单的，感谢大佬的项目，后续如有更新版本我会尽可能及时维护pypi的版本号~~
