### ISSUE TITLE
👑[Enhancement] 大型重构

### ISSUE THREAD

**Issue by misaka10843** [misaka10843/copymanga-downloader#53]
### 🥰 需求描述(Description)

因为现在添加新功能时看见之前自己写的代码多多少少有点问题，并且也并不怎么好维护，所以准备直接重新编写

### 🧐 解决方案(Solution)

全部功能重写，并且添加多线程与订阅系统

并且考虑将下载完的漫画直接转换成cbz

#### 需要关注的其他的功能修复或新增

- [x] #35 
- [x] #23 
- [x] #54 
- [x] #55 
- [x] API访问限制（防止大面积被ban，而且减轻服务器压力）
- [x] 重构收藏导出功能

**Comment by misaka10843** [comment]
重构后的一些运行截图

![image](https://user-images.githubusercontent.com/69132853/228487523-71d9e7bd-448d-4a21-9dd5-e65ece6aef3f.png)

**Comment by zddgitee** [comment]
希望大佬能补充一个一键更新收藏漫画最近更新内容的功能，和本地内容识别并跳过已下载内容
https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_modifier这个api是按照添加到书架新旧来排序
https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_updated就是按最近更新的漫画排序，按limit=12 offset自动一次加12个一页，就可以按网站显示的把已更新的内容下载一下
因为基本使用大佬的软件最多几个月到半年就可以把已完结的内容全部搞定，之后就是慢慢养鱼了，隔几天更新一波即可，但目前得自己去手动有点麻烦，而且没法跳过本地已有内容，第一是费时间，其次浪费网站流量

**Comment by misaka10843** [comment]
> 希望大佬能补充一个一键更新收藏漫画最近更新内容的功能，和本地内容识别并跳过已下载内容 [https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_modifier这个api是按照添加到书架新旧来排序](https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_modifier%E8%BF%99%E4%B8%AAapi%E6%98%AF%E6%8C%89%E7%85%A7%E6%B7%BB%E5%8A%A0%E5%88%B0%E4%B9%A6%E6%9E%B6%E6%96%B0%E6%97%A7%E6%9D%A5%E6%8E%92%E5%BA%8F) [https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_updated就是按最近更新的漫画排序，按limit=12](https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_updated%E5%B0%B1%E6%98%AF%E6%8C%89%E6%9C%80%E8%BF%91%E6%9B%B4%E6%96%B0%E7%9A%84%E6%BC%AB%E7%94%BB%E6%8E%92%E5%BA%8F%EF%BC%8C%E6%8C%89limit=12) offset自动一次加12个一页，就可以按网站显示的把已更新的内容下载一下 因为基本使用大佬的软件最多几个月到半年就可以把已完结的内容全部搞定，之后就是慢慢养鱼了，隔几天更新一波即可，但目前得自己去手动有点麻烦，而且没法跳过本地已有内容，第一是费时间，其次浪费网站流量

ReMake分支已经可以跳过本地已有内容啦，这几天准备会将收藏部分和命令行部分写出来，之后应该就可以直接获取到所有的收藏漫画并且检查是否更新+下载更新后的漫画

**Comment by misaka10843** [comment]
> 希望大佬能补充一个一键更新收藏漫画最近更新内容的功能，和本地内容识别并跳过已下载内容 [https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_modifier这个api是按照添加到书架新旧来排序](https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_modifier%E8%BF%99%E4%B8%AAapi%E6%98%AF%E6%8C%89%E7%85%A7%E6%B7%BB%E5%8A%A0%E5%88%B0%E4%B9%A6%E6%9E%B6%E6%96%B0%E6%97%A7%E6%9D%A5%E6%8E%92%E5%BA%8F) [https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_updated就是按最近更新的漫画排序，按limit=12](https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_updated%E5%B0%B1%E6%98%AF%E6%8C%89%E6%9C%80%E8%BF%91%E6%9B%B4%E6%96%B0%E7%9A%84%E6%BC%AB%E7%94%BB%E6%8E%92%E5%BA%8F%EF%BC%8C%E6%8C%89limit=12) offset自动一次加12个一页，就可以按网站显示的把已更新的内容下载一下 因为基本使用大佬的软件最多几个月到半年就可以把已完结的内容全部搞定，之后就是慢慢养鱼了，隔几天更新一波即可，但目前得自己去手动有点麻烦，而且没法跳过本地已有内容，第一是费时间，其次浪费网站流量

现在暂时考虑的是将漫画添加到一个json中进行更新（这样好管理一些qwq）

![image](https://user-images.githubusercontent.com/69132853/229052724-67e25e6b-def2-4d5d-8a3a-f0a0119c1dd7.png)

**Comment by misaka10843** [comment]
> 希望大佬能补充一个一键更新收藏漫画最近更新内容的功能，和本地内容识别并跳过已下载内容 [https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_modifier这个api是按照添加到书架新旧来排序](https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_modifier%E8%BF%99%E4%B8%AAapi%E6%98%AF%E6%8C%89%E7%85%A7%E6%B7%BB%E5%8A%A0%E5%88%B0%E4%B9%A6%E6%9E%B6%E6%96%B0%E6%97%A7%E6%9D%A5%E6%8E%92%E5%BA%8F) [https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_updated就是按最近更新的漫画排序，按limit=12](https://copymanga.org/api/v3/member/collect/comics?limit=50&offset=0&free_type=1&ordering=-datetime_updated%E5%B0%B1%E6%98%AF%E6%8C%89%E6%9C%80%E8%BF%91%E6%9B%B4%E6%96%B0%E7%9A%84%E6%BC%AB%E7%94%BB%E6%8E%92%E5%BA%8F%EF%BC%8C%E6%8C%89limit=12) offset自动一次加12个一页，就可以按网站显示的把已更新的内容下载一下 因为基本使用大佬的软件最多几个月到半年就可以把已完结的内容全部搞定，之后就是慢慢养鱼了，隔几天更新一波即可，但目前得自己去手动有点麻烦，而且没法跳过本地已有内容，第一是费时间，其次浪费网站流量

基本上已经写完了，一些功能的预览

![image](https://user-images.githubusercontent.com/69132853/229077020-c830730e-9604-49c0-8f77-c722c3866614.png)
![image](https://user-images.githubusercontent.com/69132853/229084034-eaba5b5c-10d0-46f2-9333-7cc7160fc11f.png)

**Comment by buiawpkgew1** [comment]
下载完成能打包压缩文件吗？

**Comment by misaka10843** [comment]
> @misaka10843 下载完成能打包压缩文件吗？

暂时并不能，但是您可以参考 #54 中的解决方案

**Comment by hyrulelinks** [comment]
新版本初始化设置必须要登录token或账号密码才行吗？可否增加不登录的选项？
