### ISSUE TITLE
高画质提升

### ISSUE THREAD

**Issue by X-yael** [misaka10843/copymanga-downloader#58]
图片链接中的c800替换成c1500

**Comment by misaka10843** [comment]
这个虽然可以添加，但是考虑到copymanga的服务器的话，可能会将每分钟请求量再次减少以保证不会被ban

但是还是会添加的qwq

**Comment by misaka10843** [comment]
此功能已经完成，更新到新的版本后就会进行重新设置啦！
![image](https://user-images.githubusercontent.com/69132853/234293085-3fd8ae46-ca5c-4dc7-8c00-dbc5962e2567.png)
