### ISSUE TITLE
关于批量下载的一个小建议👑[Enhancement] 

### ISSUE THREAD

**Issue by cangkuai** [misaka10843/copymanga-downloader#64]
### 🥰 需求描述(Description)

目前如果选择范围下载的话开始和结束话真的很容易搞错，建议给一个提示

### 🧐 解决方案(Solution)

就是在输入话数的索引的时候显示本话的标题，让用户确认，我看下载的时候是显示了标题的，我感觉应该不难吧

**Comment by misaka10843** [comment]
当然可以qwq

**Comment by cangkuai** [comment]
我给你发了一个邮件你看一下

**Comment by cangkuai** [comment]
因为我感觉这不算issue发这里不合适
