### ISSUE TITLE
👑[Enhancement] 

### ISSUE THREAD

**Issue by xlyytcy04** [misaka10843/copymanga-downloader#69]
### 🥰 需求描述(Description)

如图，当进入程序以后我输入2查看收藏然后程序就报错了 @misaka10843，求解答

### 🧐 解决方案(Solution)

。

### Additional context/其他信息

<img width="1280" alt="2023-05-24 (2)" src="https://github.com/misaka10843/copymanga-downloader/assets/110395382/39b48967-9fc0-4540-9a9c-f59b6431feaf">
<img width="1280" alt="2023-05-24 (1)" src="https://github.com/misaka10843/copymanga-downloader/assets/110395382/4a12fbcb-9a85-4e7a-8504-26eef4934eee">
<img width="1280" alt="2023-05-24 (3)" src="https://github.com/misaka10843/copymanga-downloader/assets/110395382/5c266107-013d-4500-bee1-d9e4e0a520f2">

**Comment by misaka10843** [comment]
请添加代理尝试，似乎你是无法访问到API

**Comment by xlyytcy04** [comment]
用了机场后解决了
