### ISSUE TITLE
👑[Enhancement] 大型重构(暂定)

### ISSUE THREAD

**Issue by misaka10843** [misaka10843/copymanga-downloader#71]
### 🥰 需求描述(Description)

因为发现屎山代码无法大型改动

导致无法进行GUI化

所以准备重新编写，将一些功能编写成类

并且准备使用vue与ws来GUI化

### 🧐 解决方案(Solution)

大型重构

并且使用vue来搭建页面

然后使用ws来进行通信

### 重构后暂定的功能列表

- [ ] 半自动更新
- [ ] 多线程下载
- [ ] GUI显示
- [ ] 添加CBZ支持
- [ ] 收藏导出
- [ ] epub打包及推送kindle
- [ ] 命令行支持

### 关联issue
- [x] #83 
- [ ] #26

**Comment by buiawpkgew1** [comment]
我关注了

**Comment by misaka10843** [comment]
关闭原因：https://github.com/misaka10843/copymanga-downloader?tab=readme-ov-file#qa%EF%B8%8F
