### ISSUE TITLE
👑[Enhancement] 替换漫画名的特殊字符

### ISSUE THREAD

**Issue by KZR001** [misaka10843/copymanga-downloader#73]
### 🥰 需求描述(Description)

因为要下载的漫画名称中包含特殊字符，软件无法创建下载文件夹而退出

### 🧐 解决方案(Solution)

能否指定下载路径或者使用字符串过滤掉漫画名称这些特殊字符从而能在Windows下创建该文件夹下载漫画？

### Additional context/其他信息

![image](https://github.com/misaka10843/copymanga-downloader/assets/103943449/84a25437-60e3-49d3-acef-6dcfc23f9f1c)

**Comment by misaka10843** [comment]
当然可以，稍后会发布修复后的版本qwq

**Comment by misaka10843** [comment]
你可以尝试一下这个版本？
https://github.com/misaka10843/copymanga-downloader/actions/runs/5537991334

**Comment by KZR001** [comment]
能够正常创建下载目录（特殊字符没有了）开始下载漫画，但是下载完成后软件会闪退，之前的版本没有这个问题，基本能用

**Comment by misaka10843** [comment]
最近有其他的几个项目在做，如果勉强能用的话那就等其他做完之后再就这个吧qwq

**Comment by misaka10843** [comment]
> 能够正常创建下载目录（特殊字符没有了）开始下载漫画，但是下载完成后软件会闪退，之前的版本没有这个问题，基本能用

请问当前还有这个问题吗，如果有的话还请在cmd中启动软件然后截图/复制闪退日志新创建一个issue，感谢支持与理解
