### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by SIEGBAR** [misaka10843/copymanga-downloader#74]
没办法下多话，下载一话后会报错退出，如图所示，如何解决？（纯小白）@misaka10843
![VVAOQY%_R2FMLVLL12J5G_V](https://github.com/misaka10843/copymanga-downloader/assets/105774465/aed35349-1fb2-4617-a7d3-f15c74d7d20b)

**Comment by SIEGBAR** [comment]
现在发现，我把打包CBZ关闭，就能正常运行了，怎么回事

**Comment by misaka10843** [comment]
似乎是因为创建cbz的时候没有创建对应的temp目录导致的
