### ISSUE TITLE
🐛[BUG] Error:Authentication credentials were not provided.

### ISSUE THREAD

**Issue by dfmjndm** [misaka10843/copymanga-downloader#81]
[root@VM-8-2-centos copymanga-downloader]# python3.9 main.py
命令行参数中缺少必要字段,将切换到普通模式
您是想搜索还是查看您的收藏？(0:导出收藏,1:搜索,2:收藏,3:添加半自动更新,9:修改设置) [0/1/2/3/9] (1): 0
请问是输出json格式还是csv格式？(0:json,1:csv) [0/1] (1): 1
无法获取到相关信息，请检查相关设置。Error:Authentication credentials were not provided.
[root@VM-8-2-centos copymanga-downloader]# 

setting中token正确

**Comment by misaka10843** [comment]
请尝试查询收藏，因为返回错误的是API服务器，所以八成是因为token的格式问题（确定格式为`Token 1293asd123s8adhh2juhsada2`）

**Comment by misaka10843** [comment]
并没有提供更多信息，暂时关闭此issue
