### ISSUE TITLE
🐛[BUG] 范围下载缺少结束下载的话数

### ISSUE THREAD

**Issue by torakiss** [misaka10843/copymanga-downloader#88]
比如某本漫画分别有1、1.5、2、3，使用范围下载，此时提示共有4话，下载选择从第1话开始，到第4话结束，实际下载回来会是1、1.5、2，缺少最后的一话。个人觉得这个范围应该是要包含尾部的吧

**Comment by misaka10843** [comment]
问题已修复，在链接的pull合并之后应该就可以了qwq
