### ISSUE TITLE
🐛[BUG] V3.5 exe文件 配置文件无法更新

### ISSUE THREAD

**Issue by 147258-gif** [misaka10843/copymanga-downloader#90]
### 📷 复现步骤(Steps to Reproduce)

1.进入配置到  “是否要修改登陆方式？”  时出现错误

### 🚑 基本信息(Basic Information)

- 程序版本或action构件日期(Program Version or Action component date): V3.5
- 系统(OS): Windows 11 23H2
- 是否使用了代理(Are agents used): 是
- prthon版本：3.8.1

### 🖼 截图
<img width="477" alt="Snipaste_2024-02-03_17-34-46" src="https://github.com/misaka10843/copymanga-downloader/assets/58428549/9b0ea48c-a233-44f1-a4dd-48b8f10c887c">
(Screenshots)

**Comment by misaka10843** [comment]
此问题似乎因为是直接启动程序所导致的，可以尝试一下用命令行启动暂且规避此问题

**Comment by 147258-gif** [comment]
这就是命令行启动

**Comment by misaka10843** [comment]
尝试使用一下源码更改？
我这边的话是没有问题的

**Comment by 947132885** [comment]
settings.py里面的load_settings函数检查必要字段时漏掉了loginPattern，加上就可以了

**Comment by misaka10843** [comment]
我姑且以因为旧版配置文件缺少loginPattern而无法升级到新版的配置文件 原因进行归纳，马上会进行更新，如果不是此原因在pull之后请重新打开此issue
