### ISSUE TITLE
👑[Enhancement] 初始化设置关于登录方式，是否可以增加不登录的选项？

### ISSUE THREAD

**Issue by hyrulelinks** [misaka10843/copymanga-downloader#93]
### 🥰 需求描述(Description)

token，但提取token过程比较复杂
账号密码，在配置文件中明文保存账号密码有一定安全风险，特别是很多其他账号用的是同一个密码的时候
不输入token或账号密码就无法完成初始化设置

### 🧐 解决方案(Solution)

@misaka10843 希望初始化设置时能增加不登录的选项

**Comment by misaka10843** [comment]
密码并不是明文存储的，只是在登录的时候会明文传输到copymanga服务器，服务器会返回密码的加盐状态以及盐

但是不登录选项似乎是因为添加账号密码登录的时候删除了（这一部分我并没有实际测试过），稍等会更新qwq

**Comment by hyrulelinks** [comment]
> 密码并不是明文存储的，只是在登录的时候会明文传输到copymanga服务器，服务器会返回密码的加盐状态以及盐
> 
> 但是不登录选项似乎是因为添加账号密码登录的时候删除了（这一部分我并没有实际测试过），稍等会更新qwq

好像还未修复不登录选项

**Comment by misaka10843** [comment]
现在应该可以了
![image](https://github.com/misaka10843/copymanga-downloader/assets/69132853/1c6cb440-f90f-42d1-a63e-7f2675907e17)

**Comment by hyrulelinks** [comment]
测试确认修复了，另外我更新了下setup.py，补上了缺的模块
