### ISSUE TITLE
🐛[BUG]账号无法登陆 

### ISSUE THREAD

**Issue by hugo1120** [misaka10843/copymanga-downloader#98]
### 🐛 描述(Description)

账号无法登陆 然后输入账号密码后卡了一会儿又让我输入 如此死循环

### 📷 复现步骤(Steps to Reproduce)

1.
2.
3.

### 程序版本(Program version)

3.5.1

### 系统(OS)

Windows10~+

### 是否使用了代理(Whether a proxy is used)

No

**Comment by hugo1120** [comment]
@misaka10843

**Comment by misaka10843** [comment]
是否有任何报错日志呢，没有相关日志/截图的情况下不好判断

**Comment by hugo1120** [comment]
好的 稍后截图



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月22日 16:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [misaka10843/copymanga-downloader] 🐛[BUG]账号无法登陆  (Issue #98) |

是否有任何报错日志呢，没有相关日志/截图的情况下不好判断
